# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/temp/cuSolverRf-batch-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/temp/cuSolverRf-batch-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/temp/cuSolverRf-batch-master/CMakeFiles /mnt/c/temp/cuSolverRf-batch-master//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/temp/cuSolverRf-batch-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mmio

# Build rule for target.
mmio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mmio
.PHONY : mmio

# fast build rule for target.
mmio/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmio.dir/build.make CMakeFiles/mmio.dir/build
.PHONY : mmio/fast

#=============================================================================
# Target rules for targets named cuSolverRf

# Build rule for target.
cuSolverRf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cuSolverRf
.PHONY : cuSolverRf

# fast build rule for target.
cuSolverRf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuSolverRf.dir/build.make CMakeFiles/cuSolverRf.dir/build
.PHONY : cuSolverRf/fast

#=============================================================================
# Target rules for targets named cuSolverRfBatch

# Build rule for target.
cuSolverRfBatch: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cuSolverRfBatch
.PHONY : cuSolverRfBatch

# fast build rule for target.
cuSolverRfBatch/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuSolverRfBatch.dir/build.make CMakeFiles/cuSolverRfBatch.dir/build
.PHONY : cuSolverRfBatch/fast

cuSolverRf.o: cuSolverRf.cpp.o
.PHONY : cuSolverRf.o

# target to build an object file
cuSolverRf.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuSolverRf.dir/build.make CMakeFiles/cuSolverRf.dir/cuSolverRf.cpp.o
.PHONY : cuSolverRf.cpp.o

cuSolverRf.i: cuSolverRf.cpp.i
.PHONY : cuSolverRf.i

# target to preprocess a source file
cuSolverRf.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuSolverRf.dir/build.make CMakeFiles/cuSolverRf.dir/cuSolverRf.cpp.i
.PHONY : cuSolverRf.cpp.i

cuSolverRf.s: cuSolverRf.cpp.s
.PHONY : cuSolverRf.s

# target to generate assembly for a file
cuSolverRf.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuSolverRf.dir/build.make CMakeFiles/cuSolverRf.dir/cuSolverRf.cpp.s
.PHONY : cuSolverRf.cpp.s

cuSolverRfBatch.o: cuSolverRfBatch.cpp.o
.PHONY : cuSolverRfBatch.o

# target to build an object file
cuSolverRfBatch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuSolverRfBatch.dir/build.make CMakeFiles/cuSolverRfBatch.dir/cuSolverRfBatch.cpp.o
.PHONY : cuSolverRfBatch.cpp.o

cuSolverRfBatch.i: cuSolverRfBatch.cpp.i
.PHONY : cuSolverRfBatch.i

# target to preprocess a source file
cuSolverRfBatch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuSolverRfBatch.dir/build.make CMakeFiles/cuSolverRfBatch.dir/cuSolverRfBatch.cpp.i
.PHONY : cuSolverRfBatch.cpp.i

cuSolverRfBatch.s: cuSolverRfBatch.cpp.s
.PHONY : cuSolverRfBatch.s

# target to generate assembly for a file
cuSolverRfBatch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuSolverRfBatch.dir/build.make CMakeFiles/cuSolverRfBatch.dir/cuSolverRfBatch.cpp.s
.PHONY : cuSolverRfBatch.cpp.s

mmio.o: mmio.c.o
.PHONY : mmio.o

# target to build an object file
mmio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmio.dir/build.make CMakeFiles/mmio.dir/mmio.c.o
.PHONY : mmio.c.o

mmio.i: mmio.c.i
.PHONY : mmio.i

# target to preprocess a source file
mmio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmio.dir/build.make CMakeFiles/mmio.dir/mmio.c.i
.PHONY : mmio.c.i

mmio.s: mmio.c.s
.PHONY : mmio.s

# target to generate assembly for a file
mmio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmio.dir/build.make CMakeFiles/mmio.dir/mmio.c.s
.PHONY : mmio.c.s

mmio_wrapper.o: mmio_wrapper.cpp.o
.PHONY : mmio_wrapper.o

# target to build an object file
mmio_wrapper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuSolverRf.dir/build.make CMakeFiles/cuSolverRf.dir/mmio_wrapper.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuSolverRfBatch.dir/build.make CMakeFiles/cuSolverRfBatch.dir/mmio_wrapper.cpp.o
.PHONY : mmio_wrapper.cpp.o

mmio_wrapper.i: mmio_wrapper.cpp.i
.PHONY : mmio_wrapper.i

# target to preprocess a source file
mmio_wrapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuSolverRf.dir/build.make CMakeFiles/cuSolverRf.dir/mmio_wrapper.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuSolverRfBatch.dir/build.make CMakeFiles/cuSolverRfBatch.dir/mmio_wrapper.cpp.i
.PHONY : mmio_wrapper.cpp.i

mmio_wrapper.s: mmio_wrapper.cpp.s
.PHONY : mmio_wrapper.s

# target to generate assembly for a file
mmio_wrapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuSolverRf.dir/build.make CMakeFiles/cuSolverRf.dir/mmio_wrapper.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuSolverRfBatch.dir/build.make CMakeFiles/cuSolverRfBatch.dir/mmio_wrapper.cpp.s
.PHONY : mmio_wrapper.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cuSolverRf"
	@echo "... cuSolverRfBatch"
	@echo "... mmio"
	@echo "... cuSolverRf.o"
	@echo "... cuSolverRf.i"
	@echo "... cuSolverRf.s"
	@echo "... cuSolverRfBatch.o"
	@echo "... cuSolverRfBatch.i"
	@echo "... cuSolverRfBatch.s"
	@echo "... mmio.o"
	@echo "... mmio.i"
	@echo "... mmio.s"
	@echo "... mmio_wrapper.o"
	@echo "... mmio_wrapper.i"
	@echo "... mmio_wrapper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

